name: DeploymentToDev

# Deploy to Dev. We only want this on non-main branches.
# TODO:
# * in an ideal world this is reusable workflow between dev & prod
# * look at concurrency, how do we avoid multiple branches tromping on each other? Do we need to?

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

on:
  push:
    branches-ignore:
      - main
  
jobs:
  deploy-to-development:
    concurrency: development
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from the mhartdev account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::609880104368:role/GitHubAction-rtkmhart-AssumeRoleWithAction
        aws-region: us-east-2
        role-session-name: githubaction-rtkmhart-wordpress-ecs-efs-rds
    - name: Test AWS OIDC Connector with GetCallerIdentity
      run: |
        aws sts get-caller-identity
    - name: Deploy VPC to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: VPCStack
        template: cfn/vpc.yaml
        parameter-overrides: file:///${{ github.workspace }}/cfn/vpc-parameters-development.json
        role-arn: arn:aws:iam::609880104368:role/GitHubActionsCFNDeploy
# 
#   deploy-to-prod:
#     # ensure test deploy is successful first
#     needs: deploy-to-test
#     concurrency: production
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Configure AWS credentials from the mhartprod account
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: arn:aws:iam::701918612521:role/TODOFIXME
#         aws-region: us-east-2

