# name: Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy-to-test:
#     concurrency: test
#     runs-on: ubuntu-latest
#     environment: test
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Configure AWS credentials from the mhartdev account
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: arn:aws:iam::609880104368:role/TODOFIXME
#         aws-region: us-east-2

#   deploy-to-prod:
#     # ensure test deploy is successful first
#     needs: deploy-to-test
#     concurrency: production
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Configure AWS credentials from the mhartprod account
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: arn:aws:iam::701918612521:role/TODOFIXME
#         aws-region: us-east-2

